Add OS and arch to zip file names
That was it is more clear which version is inside the zip file.

diff --git a/install.sh.erb b/install.sh.erb
--- a/install.sh.erb
+++ b/install.sh.erb
@@ -37,7 +37,8 @@ runningAmd64 ()
 
 running386 ()
 {
-    local arch="$(uname -m)"
+    local arch
+    arch="$(uname -m)"
     [ "$arch" = 'i686' ] || [ "$arch" = 'i386' ]
 }
 
@@ -61,7 +62,7 @@ linux_link ()
 
 downlink_link ()
 {
-    curl -o "${1}/<%= Helpers.zip_name %>" "${2}" || die "Error downloading <%= Helpers.zip_name %>.  Please check your connection and try again"
+    curl -o "${1}/<%= Helpers.bare_zip_name %>" "${2}" || die "Error downloading <%= Helpers.bare_zip_name %>.  Please check your connection and try again"
 }
 
 main ()
@@ -85,22 +86,22 @@ main ()
         die "Platform not supported by this install script.\n\n\t${color_yellow}Pre-built binaries may be available for manual download.\n\tSee:  https://github.com/FreedomBen/findref#pre-built-binaries\n"
     fi
 
-    cd "${dest_dir}"
+    cd "${dest_dir}" || die "Could not cd into ${dest_dir}"
 
     # If there's already a findref version, remove it
     cyan 'Cleaning out any old versions'
     rm -f "${bin_name}" || red "Error removing old version of ${bin_name}"
 
     cyan 'Unzipping v<%= Helpers.latest_release %>'
-    unzip '<%= Helpers.zip_name %>' || die 'Error unzipping <%= Helpers.zip_name %>'
+    unzip '<%= Helpers.bare_zip_name %>' || die 'Error unzipping <%= Helpers.bare_zip_name %>'
 
     cyan 'Cleaning up the zip file for v<%= Helpers.latest_release %>'
-    rm -f '<%= Helpers.zip_name %>' || red "Error removing <%= Helpers.zip_name %>"
+    rm -f '<%= Helpers.bare_zip_name %>' || red "Error removing <%= Helpers.bare_zip_name %>"
 
-    cyan 'Making ${bin_name} v<%= Helpers.latest_release %> executable'
+    cyan "Making ${bin_name} v<%= Helpers.latest_release %> executable"
     chmod +x "${bin_name}" || die "Unable to make $(pwd)/${bin_name}' executable!"
 
     cyan "All done!  If you can't run '${bin_name}' now, make sure that '${dest_dir}' is in your PATH"
 }
 
-main $@
+main "$@"
