Fix small bug in install script
It was displaying incorrect version numbers

diff --git a/install.sh.erb b/install.sh.erb
--- a/install.sh.erb
+++ b/install.sh.erb
@@ -37,7 +37,8 @@ runningAmd64 ()
 
 running386 ()
 {
-    local arch="$(uname -m)"
+    local arch
+    arch="$(uname -m)"
     [ "$arch" = 'i686' ] || [ "$arch" = 'i386' ]
 }
 
@@ -85,7 +86,7 @@ main ()
         die "Platform not supported by this install script.\n\n\t${color_yellow}Pre-built binaries may be available for manual download.\n\tSee:  https://github.com/FreedomBen/findref#pre-built-binaries\n"
     fi
 
-    cd "${dest_dir}"
+    cd "${dest_dir}" || die "Could not cd into ${dest_dir}"
 
     # If there's already a findref version, remove it
     cyan 'Cleaning out any old versions'
@@ -97,10 +98,10 @@ main ()
     cyan 'Cleaning up the zip file for v<%= Helpers.latest_release %>'
     rm -f '<%= Helpers.zip_name %>' || red "Error removing <%= Helpers.zip_name %>"
 
-    cyan 'Making ${bin_name} v<%= Helpers.latest_release %> executable'
+    cyan "Making ${bin_name} v<%= Helpers.latest_release %> executable"
     chmod +x "${bin_name}" || die "Unable to make $(pwd)/${bin_name}' executable!"
 
     cyan "All done!  If you can't run '${bin_name}' now, make sure that '${dest_dir}' is in your PATH"
 }
 
-main $@
+main "$@"
